"""UI event handlers extracted from web_app.py."""

from src.ui.handlers.events import (
    _apply_provider,
    _build_api_doc_text,
    _build_guide_markdown,
    _clear_history,
    _export_api_doc,
    _export_response,
    _finish_login_check,
    _health_check,
    _history_table,
    _input_tip,
    _latest_errors,
    _load_config_for_form,
    _one_click_prepare,
    _open_login_browser,
    _reuse_last_input,
    _run_smoke_test,
    _save_config_from_form,
    _run_task,
    _template_help,
    get_login_lock,
    LOGIN_STATE,
    LAST_INPUT,
)

__all__ = [
    "_apply_provider",
    "_build_api_doc_text",
    "_build_guide_markdown",
    "_clear_history",
    "_export_api_doc",
    "_export_response",
    "_finish_login_check",
    "_health_check",
    "_history_table",
    "_input_tip",
    "_latest_errors",
    "_load_config_for_form",
    "_one_click_prepare",
    "_open_login_browser",
    "_reuse_last_input",
    "_run_smoke_test",
    "_save_config_from_form",
    "_run_task",
    "_template_help",
    "get_login_lock",
    "LOGIN_STATE",
    "LAST_INPUT",
]
